// <auto-generated />
using System;
using LoanManagementSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanManagementSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818055116_AddPromiseToPay")]
    partial class AddPromiseToPay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanManagementSystem.Domain.CashLedger.CashLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ledger_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCashIn")
                        .HasColumnType("bit")
                        .HasColumnName("is_cash_in");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("remarks");

                    b.Property<Guid?>("SourcePaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("source_payment_id");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.ToTable("cash_ledger", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("address");

                    b.Property<string>("BorrowerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("borrower_type");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_number");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerNumber"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("NicknameAlias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nickname_alias");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerNumber")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Customers.CustomerDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("original_file_name");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_documents", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Diary.DiaryAuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("audit_log_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("DiaryEntryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("diary_entry_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("performed_by");

                    b.HasKey("Id");

                    b.HasIndex("DiaryEntryId");

                    b.ToTable("diary_audit_log", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Diary.DiaryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<string>("DisplayColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("display_color");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("diary_categories", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Diary.DiaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("diary_entry_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<TimeOnly>("EntryTime")
                        .HasColumnType("time")
                        .HasColumnName("entry_time");

                    b.Property<Guid?>("LoanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("ReminderDate")
                        .HasColumnType("date")
                        .HasColumnName("reminder_date");

                    b.Property<TimeOnly?>("ReminderTime")
                        .HasColumnType("time")
                        .HasColumnName("reminder_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EntryDate");

                    b.HasIndex("LoanId");

                    b.ToTable("diary_entries", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Diary.DiaryFinancialSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("snapshot_id");

                    b.Property<int>("ActiveLoanCount")
                        .HasColumnType("int")
                        .HasColumnName("active_loan_count");

                    b.Property<int>("BadLoanCount")
                        .HasColumnType("int")
                        .HasColumnName("bad_loan_count");

                    b.Property<decimal>("BadLoanReceivables")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("bad_loan_receivables");

                    b.Property<decimal>("CashOnHand")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("cash_on_hand");

                    b.Property<decimal>("CollectibleReceivables")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("collectible_receivables");

                    b.Property<decimal>("CollectionsMonthToDate")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("collections_month_to_date");

                    b.Property<decimal>("CollectionsToday")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("collections_today");

                    b.Property<Guid>("DiaryEntryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("diary_entry_id");

                    b.Property<decimal>("GrossReceivables")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gross_receivables");

                    b.Property<decimal>("LoanReleasesMonthToDate")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("loan_releases_month_to_date");

                    b.Property<decimal>("LoanReleasesToday")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("loan_releases_today");

                    b.Property<int>("OverdueLoanCount")
                        .HasColumnType("int")
                        .HasColumnName("overdue_loan_count");

                    b.Property<DateTime>("SnapshotDateTimeUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("snapshot_datetime");

                    b.HasKey("Id");

                    b.HasIndex("DiaryEntryId")
                        .IsUnique();

                    b.ToTable("diary_financial_snapshots", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Loans.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("balance");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("interest_rate");

                    b.Property<int>("LoanNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("loan_number");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanNumber"));

                    b.Property<int>("PaymentTermsMonths")
                        .HasColumnType("int")
                        .HasColumnName("payment_terms_months");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("principal_amount");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("remarks");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmountDue")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_amount_due");

                    b.Property<decimal>("TotalExtensionCharges")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_extension_charges");

                    b.Property<decimal>("TotalInterest")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_interest");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_paid");

                    b.HasKey("Id");

                    b.HasIndex("LoanNumber")
                        .IsUnique();

                    b.ToTable("loans", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Loans.LoanAuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("audit_log_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("performed_by");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("loan_audit_log", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Loans.LoanDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content_type");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("original_file_name");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("loan_documents", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Loans.LoanExtension", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("extension_id");

                    b.Property<decimal>("AdditionalChargesAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("additional_charges_amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("ExtensionDate")
                        .HasColumnType("date")
                        .HasColumnName("extension_date");

                    b.Property<int>("ExtensionDays")
                        .HasColumnType("int")
                        .HasColumnName("extension_days");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("remarks");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("loan_extensions", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Loans.LoanLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ledger_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("debit");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("remarks");

                    b.Property<decimal>("RunningBalance")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("running_balance");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("loan_ledger", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Loans.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount_paid");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("payment_method");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reference_number");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Promises.PromiseAuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("audit_log_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("performed_by");

                    b.Property<Guid>("PromiseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("promise_id");

                    b.HasKey("Id");

                    b.HasIndex("PromiseId");

                    b.ToTable("promise_audit_log", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Promises.PromiseToPay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("promise_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PromiseDate")
                        .HasColumnType("date")
                        .HasColumnName("promise_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoanId");

                    b.HasIndex("PromiseDate");

                    b.ToTable("promises_to_pay", (string)null);
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Customers.CustomerDocument", b =>
                {
                    b.HasOne("LoanManagementSystem.Domain.Customers.Customer", null)
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Diary.DiaryFinancialSnapshot", b =>
                {
                    b.HasOne("LoanManagementSystem.Domain.Diary.DiaryEntry", null)
                        .WithOne("Snapshot")
                        .HasForeignKey("LoanManagementSystem.Domain.Diary.DiaryFinancialSnapshot", "DiaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Loans.LoanDocument", b =>
                {
                    b.HasOne("LoanManagementSystem.Domain.Loans.Loan", null)
                        .WithMany("Documents")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Loans.LoanExtension", b =>
                {
                    b.HasOne("LoanManagementSystem.Domain.Loans.Loan", null)
                        .WithMany("Extensions")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Loans.Payment", b =>
                {
                    b.HasOne("LoanManagementSystem.Domain.Loans.Loan", null)
                        .WithMany("Payments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Customers.Customer", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Diary.DiaryEntry", b =>
                {
                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("LoanManagementSystem.Domain.Loans.Loan", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Extensions");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
